# This is a basic workflow to help you get started with Actions

name: Custom Action

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ashiishme/see-action-in-action@v2
        id: ashiishme-action
        with:
          who-to-greet: 'Hello Ashish Yadav ^_^'
        
      - name: Output
        run: echo '${{ steps.ashiishme-action.outputs.time }}'
